# Generated by Django 5.2.6 on 2026-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_rule_code_rule_description_rule_is_system'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='access_type',
            field=models.CharField(default='OPEN', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='governance_type',
            field=models.CharField(default='MEDIUM', max_length=50),
        ),
    ]
