# Generated by Django 5.2.6 on 2026-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_alter_user_managers_community_access_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('FACILITATOR', 'Facilitator'), ('CO_FACILITATOR', 'Co-Facilitator'), ('SYSTEM', 'System')], default='MEMBER', max_length=50),
        ),
    ]
