# Generated by Django 5.2.6 on 2026-01-19 12:29

from django.db import migrations


def update_roles(apps, schema_editor):
    User = apps.get_model('governance', 'User')
    User.objects.filter(role='CITIZEN').update(role='MEMBER')

def reverse_roles(apps, schema_editor):
    User = apps.get_model('governance', 'User')
    User.objects.filter(role='MEMBER').update(role='CITIZEN')

class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(update_roles, reverse_roles),
    ]
