# Generated by Django 5.2.6 on 2026-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_migrate_citizen_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
