# Generated by Django 5.2.6 on 2026-01-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_alter_communitymember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruledecision',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
