# Generated by Django 5.2.6 on 2026-01-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_ruledecision_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
