# Generated by Django 5.2.6 on 2026-01-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_community_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
