# Generated by Django 5.2.6 on 2026-01-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_user_avatar_alter_community_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discussion_images/'),
        ),
    ]
