# Generated by Django 5.2.6 on 2026-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_user_bio_user_facebook_profile_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_images/'),
        ),
    ]
