# Generated by Django 5.2.6 on 2026-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0015_boardtype_user_is_muted_user_mute_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.IntegerField(default=100),
        ),
    ]
