# Generated by Django 5.2.6 on 2026-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0016_user_reputation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_orientation',
            field=models.BooleanField(default=False),
        ),
    ]
