# Generated by Django 5.2.6 on 2026-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0019_boardrequest_invitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
