# Generated by Django 5.2.6 on 2026-03-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0020_communitymember_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technical'), ('MEDICAL', 'Medical'), ('SOCIAL', 'Social'), ('EDUCATIONAL', 'Educational'), ('CIVIC', 'Civic'), ('OTHER', 'Other')], default='SOCIAL', max_length=50),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='intent_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
