# Generated by Django 5.2.6 on 2026-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0021_community_category_communitymember_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('CO_FACILITATOR', 'Co-Facilitator'), ('FACILITATOR', 'Facilitator')], default='MEMBER', max_length=50),
        ),
    ]
