# Generated by Django 5.2.6 on 2026-03-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0023_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invitelink',
            name='community',
        ),
        migrations.RemoveField(
            model_name='invitelink',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='community',
            name='category',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='intent_category',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='role',
        ),
        migrations.AddField(
            model_name='response',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='response_images/'),
        ),
        migrations.DeleteModel(
            name='BoardRequest',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='InviteLink',
        ),
    ]
